### ISSUE TITLE
gtk3-ubuntu source not found 

### ISSUE THREAD

**Issue by justrobd** [chenxiaolong/Unity-for-Arch#237]
I was trying to build 'unity-for-arch' got the following error:
curl: (22) The requested URL returned error: 404 Not Found
==> ERROR: Failure while downloading http://ppa.launchpad.net/gnome3-team/gnome3-staging/ubuntu/pool/main/g/gtk+3.0/gtk+3.0_3.20.6-2ubuntu1~xenial2.debian.tar.xz
    Aborting...

I went to the source location and it doesn't seem to exists there either. Don't know where else to get it.

**Comment by horsemanoffaith** [comment]
This issue is previously mentioned in #228 and #235. If you look at the source location you'll find that 3.20.6 had been replaced with 3.20.8. Edit the PKGBUILD with the corresponding version in the source location and it should work just fine. If you're really having issues, just use my Unity-for-Arch Github page. I recently updated all the files, and unless there's new updates in the last two weeks, you should be able to build everything without a hitch.

https://github.com/horsemanffaith/Unity-for-Arch

**Comment by justrobd** [comment]
Cool thanks for the reply. I saw those issues #228 and #235 as well when I tried those I was still getting the 404 Not Found. I will give yours a try. Thanks again..
